#!/usr/bin/env python
import sys
import os

os.environ['CERBERO_UNINSTALLED']='1'
__dir__=os.path.abspath( os.path.dirname(__file__) )
sys.path.insert(0, __dir__)
sys.path.insert(0, os.path.join(__dir__,'cerbero'))

from hacks import hijack
from cerbero.main import main
main()
